// Code generated by MockGen. DO NOT EDIT.
// Source: db.go

// Package db is a generated GoMock package.
package db

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	condition "tounilab.com/db-connector/pkg/query/condition"
	options "tounilab.com/db-connector/pkg/query/options"
)

// MockDBConfig is a mock of DBConfig interface.
type MockDBConfig struct {
	ctrl     *gomock.Controller
	recorder *MockDBConfigMockRecorder
}

// MockDBConfigMockRecorder is the mock recorder for MockDBConfig.
type MockDBConfigMockRecorder struct {
	mock *MockDBConfig
}

// NewMockDBConfig creates a new mock instance.
func NewMockDBConfig(ctrl *gomock.Controller) *MockDBConfig {
	mock := &MockDBConfig{ctrl: ctrl}
	mock.recorder = &MockDBConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBConfig) EXPECT() *MockDBConfigMockRecorder {
	return m.recorder
}

// DSN mocks base method.
func (m *MockDBConfig) DSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// DSN indicates an expected call of DSN.
func (mr *MockDBConfigMockRecorder) DSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DSN", reflect.TypeOf((*MockDBConfig)(nil).DSN))
}

// Driver mocks base method.
func (m *MockDBConfig) Driver() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Driver")
	ret0, _ := ret[0].(string)
	return ret0
}

// Driver indicates an expected call of Driver.
func (mr *MockDBConfigMockRecorder) Driver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Driver", reflect.TypeOf((*MockDBConfig)(nil).Driver))
}

// MockDBActions is a mock of DBActions interface.
type MockDBActions struct {
	ctrl     *gomock.Controller
	recorder *MockDBActionsMockRecorder
}

// MockDBActionsMockRecorder is the mock recorder for MockDBActions.
type MockDBActionsMockRecorder struct {
	mock *MockDBActions
}

// NewMockDBActions creates a new mock instance.
func NewMockDBActions(ctrl *gomock.Controller) *MockDBActions {
	mock := &MockDBActions{ctrl: ctrl}
	mock.recorder = &MockDBActionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBActions) EXPECT() *MockDBActionsMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDBActions) Delete(ctx context.Context, table string, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, table, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDBActionsMockRecorder) Delete(ctx, table, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDBActions)(nil).Delete), ctx, table, conditions, opts)
}

// Exec mocks base method.
func (m *MockDBActions) Exec(ctx context.Context, query string, args ...any) (*ExecResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBActionsMockRecorder) Exec(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDBActions)(nil).Exec), varargs...)
}

// Get mocks base method.
func (m *MockDBActions) Get(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDBActionsMockRecorder) Get(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDBActions)(nil).Get), ctx, table, columns, joins, conditions, opts)
}

// GetByID mocks base method.
func (m *MockDBActions) GetByID(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, table, id, joins, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDBActionsMockRecorder) GetByID(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDBActions)(nil).GetByID), ctx, table, id, joins, opts)
}

// GetByIDRaw mocks base method.
func (m *MockDBActions) GetByIDRaw(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDRaw", ctx, table, id, joins, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDRaw indicates an expected call of GetByIDRaw.
func (mr *MockDBActionsMockRecorder) GetByIDRaw(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDRaw", reflect.TypeOf((*MockDBActions)(nil).GetByIDRaw), ctx, table, id, joins, opts)
}

// GetRaw mocks base method.
func (m *MockDBActions) GetRaw(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRaw", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRaw indicates an expected call of GetRaw.
func (mr *MockDBActionsMockRecorder) GetRaw(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRaw", reflect.TypeOf((*MockDBActions)(nil).GetRaw), ctx, table, columns, joins, conditions, opts)
}

// Insert mocks base method.
func (m *MockDBActions) Insert(ctx context.Context, table string, data map[string]any, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, table, data, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockDBActionsMockRecorder) Insert(ctx, table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDBActions)(nil).Insert), ctx, table, data, opts)
}

// Query mocks base method.
func (m *MockDBActions) Query(ctx context.Context, query string, args ...any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDBActionsMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDBActions)(nil).Query), varargs...)
}

// QueryRaw mocks base method.
func (m *MockDBActions) QueryRaw(ctx context.Context, query string, args ...any) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRaw", varargs...)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryRaw indicates an expected call of QueryRaw.
func (mr *MockDBActionsMockRecorder) QueryRaw(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRaw", reflect.TypeOf((*MockDBActions)(nil).QueryRaw), varargs...)
}

// Update mocks base method.
func (m *MockDBActions) Update(ctx context.Context, table string, data map[string]any, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, table, data, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDBActionsMockRecorder) Update(ctx, table, data, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDBActions)(nil).Update), ctx, table, data, conditions, opts)
}

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDB) Begin(ctx context.Context) (Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockDBMockRecorder) Begin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDB)(nil).Begin), ctx)
}

// Close mocks base method.
func (m *MockDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDB)(nil).Close))
}

// Delete mocks base method.
func (m *MockDB) Delete(ctx context.Context, table string, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, table, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDBMockRecorder) Delete(ctx, table, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDB)(nil).Delete), ctx, table, conditions, opts)
}

// Exec mocks base method.
func (m *MockDB) Exec(ctx context.Context, query string, args ...any) (*ExecResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBMockRecorder) Exec(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDB)(nil).Exec), varargs...)
}

// Get mocks base method.
func (m *MockDB) Get(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDBMockRecorder) Get(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDB)(nil).Get), ctx, table, columns, joins, conditions, opts)
}

// GetByID mocks base method.
func (m *MockDB) GetByID(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, table, id, joins, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDBMockRecorder) GetByID(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDB)(nil).GetByID), ctx, table, id, joins, opts)
}

// GetByIDRaw mocks base method.
func (m *MockDB) GetByIDRaw(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDRaw", ctx, table, id, joins, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDRaw indicates an expected call of GetByIDRaw.
func (mr *MockDBMockRecorder) GetByIDRaw(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDRaw", reflect.TypeOf((*MockDB)(nil).GetByIDRaw), ctx, table, id, joins, opts)
}

// GetRaw mocks base method.
func (m *MockDB) GetRaw(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRaw", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRaw indicates an expected call of GetRaw.
func (mr *MockDBMockRecorder) GetRaw(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRaw", reflect.TypeOf((*MockDB)(nil).GetRaw), ctx, table, columns, joins, conditions, opts)
}

// Insert mocks base method.
func (m *MockDB) Insert(ctx context.Context, table string, data map[string]any, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, table, data, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockDBMockRecorder) Insert(ctx, table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDB)(nil).Insert), ctx, table, data, opts)
}

// Ping mocks base method.
func (m *MockDB) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDBMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDB)(nil).Ping), ctx)
}

// PoolStats mocks base method.
func (m *MockDB) PoolStats() (*PoolStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PoolStats")
	ret0, _ := ret[0].(*PoolStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PoolStats indicates an expected call of PoolStats.
func (mr *MockDBMockRecorder) PoolStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PoolStats", reflect.TypeOf((*MockDB)(nil).PoolStats))
}

// Query mocks base method.
func (m *MockDB) Query(ctx context.Context, query string, args ...any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDBMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDB)(nil).Query), varargs...)
}

// QueryRaw mocks base method.
func (m *MockDB) QueryRaw(ctx context.Context, query string, args ...any) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRaw", varargs...)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryRaw indicates an expected call of QueryRaw.
func (mr *MockDBMockRecorder) QueryRaw(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRaw", reflect.TypeOf((*MockDB)(nil).QueryRaw), varargs...)
}

// Update mocks base method.
func (m *MockDB) Update(ctx context.Context, table string, data map[string]any, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, table, data, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDBMockRecorder) Update(ctx, table, data, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDB)(nil).Update), ctx, table, data, conditions, opts)
}

// WithTransaction mocks base method.
func (m *MockDB) WithTransaction(ctx context.Context, fn func(Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockDBMockRecorder) WithTransaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockDB)(nil).WithTransaction), ctx, fn)
}

// MockTx is a mock of Tx interface.
type MockTx struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder struct {
	mock *MockTx
}

// NewMockTx creates a new mock instance.
func NewMockTx(ctrl *gomock.Controller) *MockTx {
	mock := &MockTx{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx) EXPECT() *MockTxMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTx) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxMockRecorder) Commit(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTx)(nil).Commit), ctx)
}

// Delete mocks base method.
func (m *MockTx) Delete(ctx context.Context, table string, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, table, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTxMockRecorder) Delete(ctx, table, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTx)(nil).Delete), ctx, table, conditions, opts)
}

// Exec mocks base method.
func (m *MockTx) Exec(ctx context.Context, query string, args ...any) (*ExecResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockTxMockRecorder) Exec(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockTx)(nil).Exec), varargs...)
}

// Get mocks base method.
func (m *MockTx) Get(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTxMockRecorder) Get(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTx)(nil).Get), ctx, table, columns, joins, conditions, opts)
}

// GetByID mocks base method.
func (m *MockTx) GetByID(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, table, id, joins, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTxMockRecorder) GetByID(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTx)(nil).GetByID), ctx, table, id, joins, opts)
}

// GetByIDRaw mocks base method.
func (m *MockTx) GetByIDRaw(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDRaw", ctx, table, id, joins, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDRaw indicates an expected call of GetByIDRaw.
func (mr *MockTxMockRecorder) GetByIDRaw(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDRaw", reflect.TypeOf((*MockTx)(nil).GetByIDRaw), ctx, table, id, joins, opts)
}

// GetRaw mocks base method.
func (m *MockTx) GetRaw(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRaw", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRaw indicates an expected call of GetRaw.
func (mr *MockTxMockRecorder) GetRaw(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRaw", reflect.TypeOf((*MockTx)(nil).GetRaw), ctx, table, columns, joins, conditions, opts)
}

// Insert mocks base method.
func (m *MockTx) Insert(ctx context.Context, table string, data map[string]any, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, table, data, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockTxMockRecorder) Insert(ctx, table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTx)(nil).Insert), ctx, table, data, opts)
}

// Query mocks base method.
func (m *MockTx) Query(ctx context.Context, query string, args ...any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockTxMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockTx)(nil).Query), varargs...)
}

// QueryRaw mocks base method.
func (m *MockTx) QueryRaw(ctx context.Context, query string, args ...any) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRaw", varargs...)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryRaw indicates an expected call of QueryRaw.
func (mr *MockTxMockRecorder) QueryRaw(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRaw", reflect.TypeOf((*MockTx)(nil).QueryRaw), varargs...)
}

// Rollback mocks base method.
func (m *MockTx) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxMockRecorder) Rollback(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTx)(nil).Rollback), ctx)
}

// Update mocks base method.
func (m *MockTx) Update(ctx context.Context, table string, data map[string]any, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, table, data, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTxMockRecorder) Update(ctx, table, data, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTx)(nil).Update), ctx, table, data, conditions, opts)
}
