//go:build test || mocks

// Code generated by MockGen. DO NOT EDIT.
// Source: builder.go

package builder

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	condition "tounilab.com/vessel/pkg/query/condition"
	definition "tounilab.com/vessel/pkg/query/definition"
	options "tounilab.com/vessel/pkg/query/options"
)

// MockoptionDialect is a mock of optionDialect interface.
type MockoptionDialect struct {
	ctrl     *gomock.Controller
	recorder *MockoptionDialectMockRecorder
}

// MockoptionDialectMockRecorder is the mock recorder for MockoptionDialect.
type MockoptionDialectMockRecorder struct {
	mock *MockoptionDialect
}

// NewMockoptionDialect creates a new mock instance.
func NewMockoptionDialect(ctrl *gomock.Controller) *MockoptionDialect {
	mock := &MockoptionDialect{ctrl: ctrl}
	mock.recorder = &MockoptionDialectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoptionDialect) EXPECT() *MockoptionDialectMockRecorder {
	return m.recorder
}

// Operator mocks base method.
func (m *MockoptionDialect) Operator(op string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Operator", op)
	ret0, _ := ret[0].(string)
	return ret0
}

// Operator indicates an expected call of Operator.
func (mr *MockoptionDialectMockRecorder) Operator(op interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Operator", reflect.TypeOf((*MockoptionDialect)(nil).Operator), op)
}

// Placeholder mocks base method.
func (m *MockoptionDialect) Placeholder(index int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Placeholder", index)
	ret0, _ := ret[0].(string)
	return ret0
}

// Placeholder indicates an expected call of Placeholder.
func (mr *MockoptionDialectMockRecorder) Placeholder(index interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Placeholder", reflect.TypeOf((*MockoptionDialect)(nil).Placeholder), index)
}

// QuoteIdentifier mocks base method.
func (m *MockoptionDialect) QuoteIdentifier(value string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuoteIdentifier", value)
	ret0, _ := ret[0].(string)
	return ret0
}

// QuoteIdentifier indicates an expected call of QuoteIdentifier.
func (mr *MockoptionDialectMockRecorder) QuoteIdentifier(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuoteIdentifier", reflect.TypeOf((*MockoptionDialect)(nil).QuoteIdentifier), value)
}

// QuoteString mocks base method.
func (m *MockoptionDialect) QuoteString(value string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuoteString", value)
	ret0, _ := ret[0].(string)
	return ret0
}

// QuoteString indicates an expected call of QuoteString.
func (mr *MockoptionDialectMockRecorder) QuoteString(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuoteString", reflect.TypeOf((*MockoptionDialect)(nil).QuoteString), value)
}

// SupportedOptions mocks base method.
func (m *MockoptionDialect) SupportedOptions(arg0 definition.QueryType, arg1 *options.QueryOptions, arg2 int) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedOptions", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SupportedOptions indicates an expected call of SupportedOptions.
func (mr *MockoptionDialectMockRecorder) SupportedOptions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedOptions", reflect.TypeOf((*MockoptionDialect)(nil).SupportedOptions), arg0, arg1, arg2)
}

// MockQueryBuilder is a mock of QueryBuilder interface.
type MockQueryBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockQueryBuilderMockRecorder
}

// MockQueryBuilderMockRecorder is the mock recorder for MockQueryBuilder.
type MockQueryBuilderMockRecorder struct {
	mock *MockQueryBuilder
}

// NewMockQueryBuilder creates a new mock instance.
func NewMockQueryBuilder(ctrl *gomock.Controller) *MockQueryBuilder {
	mock := &MockQueryBuilder{ctrl: ctrl}
	mock.recorder = &MockQueryBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryBuilder) EXPECT() *MockQueryBuilderMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockQueryBuilder) Delete(table string, joins []condition.Join, cond condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", table, joins, cond, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Delete indicates an expected call of Delete.
func (mr *MockQueryBuilderMockRecorder) Delete(table, joins, cond, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQueryBuilder)(nil).Delete), table, joins, cond, opts)
}

// Insert mocks base method.
func (m *MockQueryBuilder) Insert(table string, data map[string]any, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", table, data, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Insert indicates an expected call of Insert.
func (mr *MockQueryBuilderMockRecorder) Insert(table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockQueryBuilder)(nil).Insert), table, data, opts)
}

// Inserts mocks base method.
func (m *MockQueryBuilder) Inserts(table string, data []map[string]any, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inserts", table, data, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Inserts indicates an expected call of Inserts.
func (mr *MockQueryBuilderMockRecorder) Inserts(table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inserts", reflect.TypeOf((*MockQueryBuilder)(nil).Inserts), table, data, opts)
}

// Select mocks base method.
func (m *MockQueryBuilder) Select(table string, columns []string, joins []condition.Join, opts *options.QueryOptions, cond condition.Condition) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", table, columns, joins, opts, cond)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Select indicates an expected call of Select.
func (mr *MockQueryBuilderMockRecorder) Select(table, columns, joins, opts, cond interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockQueryBuilder)(nil).Select), table, columns, joins, opts, cond)
}

// Update mocks base method.
func (m *MockQueryBuilder) Update(table string, data map[string]any, joins []condition.Join, cond condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", table, data, joins, cond, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Update indicates an expected call of Update.
func (mr *MockQueryBuilderMockRecorder) Update(table, data, joins, cond, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQueryBuilder)(nil).Update), table, data, joins, cond, opts)
}

// Upsert mocks base method.
func (m *MockQueryBuilder) Upsert(table string, data map[string]any, upsertOpts *options.UpsertOptions, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", table, data, upsertOpts, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Upsert indicates an expected call of Upsert.
func (mr *MockQueryBuilderMockRecorder) Upsert(table, data, upsertOpts, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockQueryBuilder)(nil).Upsert), table, data, upsertOpts, opts)
}

// Upserts mocks base method.
func (m *MockQueryBuilder) Upserts(table string, data []map[string]any, upsertOpts *options.UpsertOptions, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upserts", table, data, upsertOpts, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Upserts indicates an expected call of Upserts.
func (mr *MockQueryBuilderMockRecorder) Upserts(table, data, upsertOpts, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upserts", reflect.TypeOf((*MockQueryBuilder)(nil).Upserts), table, data, upsertOpts, opts)
}
