// Code generated by MockGen. DO NOT EDIT.
// Source: builder.go

// Package builder is a generated GoMock package.
package builder

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	condition "tounilab.com/fabric/pkg/query/condition"
	options "tounilab.com/fabric/pkg/query/options"
)

// MockQueryBuilder is a mock of QueryBuilder interface.
type MockQueryBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockQueryBuilderMockRecorder
}

// MockQueryBuilderMockRecorder is the mock recorder for MockQueryBuilder.
type MockQueryBuilderMockRecorder struct {
	mock *MockQueryBuilder
}

// NewMockQueryBuilder creates a new mock instance.
func NewMockQueryBuilder(ctrl *gomock.Controller) *MockQueryBuilder {
	mock := &MockQueryBuilder{ctrl: ctrl}
	mock.recorder = &MockQueryBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryBuilder) EXPECT() *MockQueryBuilderMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockQueryBuilder) Delete(table string, joins []condition.Join, cond condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", table, joins, cond, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Delete indicates an expected call of Delete.
func (mr *MockQueryBuilderMockRecorder) Delete(table, joins, cond, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQueryBuilder)(nil).Delete), table, joins, cond, opts)
}

// Insert mocks base method.
func (m *MockQueryBuilder) Insert(table string, data map[string]any, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", table, data, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Insert indicates an expected call of Insert.
func (mr *MockQueryBuilderMockRecorder) Insert(table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockQueryBuilder)(nil).Insert), table, data, opts)
}

// Inserts mocks base method.
func (m *MockQueryBuilder) Inserts(table string, data []map[string]any, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inserts", table, data, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Inserts indicates an expected call of Inserts.
func (mr *MockQueryBuilderMockRecorder) Inserts(table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inserts", reflect.TypeOf((*MockQueryBuilder)(nil).Inserts), table, data, opts)
}

// Select mocks base method.
func (m *MockQueryBuilder) Select(table string, columns []string, joins []condition.Join, opts *options.QueryOptions, cond condition.Condition) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", table, columns, joins, opts, cond)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Select indicates an expected call of Select.
func (mr *MockQueryBuilderMockRecorder) Select(table, columns, joins, opts, cond interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockQueryBuilder)(nil).Select), table, columns, joins, opts, cond)
}

// Update mocks base method.
func (m *MockQueryBuilder) Update(table string, data map[string]any, joins []condition.Join, cond condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", table, data, joins, cond, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Update indicates an expected call of Update.
func (mr *MockQueryBuilderMockRecorder) Update(table, data, joins, cond, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQueryBuilder)(nil).Update), table, data, joins, cond, opts)
}
