//go:build test || mocks

// Code generated by MockGen. DO NOT EDIT.
// Source: db.go

package v1

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	condition "tounilab.com/vessel/pkg/query/condition"
	options "tounilab.com/vessel/pkg/query/options"
)

// MockDBConfig is a mock of DBConfig interface.
type MockDBConfig struct {
	ctrl     *gomock.Controller
	recorder *MockDBConfigMockRecorder
}

// MockDBConfigMockRecorder is the mock recorder for MockDBConfig.
type MockDBConfigMockRecorder struct {
	mock *MockDBConfig
}

// NewMockDBConfig creates a new mock instance.
func NewMockDBConfig(ctrl *gomock.Controller) *MockDBConfig {
	mock := &MockDBConfig{ctrl: ctrl}
	mock.recorder = &MockDBConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBConfig) EXPECT() *MockDBConfigMockRecorder {
	return m.recorder
}

// DSN mocks base method.
func (m *MockDBConfig) DSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// DSN indicates an expected call of DSN.
func (mr *MockDBConfigMockRecorder) DSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DSN", reflect.TypeOf((*MockDBConfig)(nil).DSN))
}

// Driver mocks base method.
func (m *MockDBConfig) Driver() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Driver")
	ret0, _ := ret[0].(string)
	return ret0
}

// Driver indicates an expected call of Driver.
func (mr *MockDBConfigMockRecorder) Driver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Driver", reflect.TypeOf((*MockDBConfig)(nil).Driver))
}

// Mockreader is a mock of reader interface.
type Mockreader struct {
	ctrl     *gomock.Controller
	recorder *MockreaderMockRecorder
}

// MockreaderMockRecorder is the mock recorder for Mockreader.
type MockreaderMockRecorder struct {
	mock *Mockreader
}

// NewMockreader creates a new mock instance.
func NewMockreader(ctrl *gomock.Controller) *Mockreader {
	mock := &Mockreader{ctrl: ctrl}
	mock.recorder = &MockreaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockreader) EXPECT() *MockreaderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *Mockreader) Get(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockreaderMockRecorder) Get(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockreader)(nil).Get), ctx, table, columns, joins, conditions, opts)
}

// GetByID mocks base method.
func (m *Mockreader) GetByID(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, table, id, joins, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockreaderMockRecorder) GetByID(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*Mockreader)(nil).GetByID), ctx, table, id, joins, opts)
}

// GetByIDRaw mocks base method.
func (m *Mockreader) GetByIDRaw(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDRaw", ctx, table, id, joins, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDRaw indicates an expected call of GetByIDRaw.
func (mr *MockreaderMockRecorder) GetByIDRaw(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDRaw", reflect.TypeOf((*Mockreader)(nil).GetByIDRaw), ctx, table, id, joins, opts)
}

// GetRaw mocks base method.
func (m *Mockreader) GetRaw(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRaw", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRaw indicates an expected call of GetRaw.
func (mr *MockreaderMockRecorder) GetRaw(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRaw", reflect.TypeOf((*Mockreader)(nil).GetRaw), ctx, table, columns, joins, conditions, opts)
}

// Query mocks base method.
func (m *Mockreader) Query(ctx context.Context, query string, args ...any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockreaderMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*Mockreader)(nil).Query), varargs...)
}

// QueryRaw mocks base method.
func (m *Mockreader) QueryRaw(ctx context.Context, query string, args ...any) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRaw", varargs...)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryRaw indicates an expected call of QueryRaw.
func (mr *MockreaderMockRecorder) QueryRaw(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRaw", reflect.TypeOf((*Mockreader)(nil).QueryRaw), varargs...)
}

// Mockwriter is a mock of writer interface.
type Mockwriter struct {
	ctrl     *gomock.Controller
	recorder *MockwriterMockRecorder
}

// MockwriterMockRecorder is the mock recorder for Mockwriter.
type MockwriterMockRecorder struct {
	mock *Mockwriter
}

// NewMockwriter creates a new mock instance.
func NewMockwriter(ctrl *gomock.Controller) *Mockwriter {
	mock := &Mockwriter{ctrl: ctrl}
	mock.recorder = &MockwriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockwriter) EXPECT() *MockwriterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *Mockwriter) Delete(ctx context.Context, table string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, table, joins, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockwriterMockRecorder) Delete(ctx, table, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockwriter)(nil).Delete), ctx, table, joins, conditions, opts)
}

// Exec mocks base method.
func (m *Mockwriter) Exec(ctx context.Context, query string, args ...any) (*ExecResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockwriterMockRecorder) Exec(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*Mockwriter)(nil).Exec), varargs...)
}

// Insert mocks base method.
func (m *Mockwriter) Insert(ctx context.Context, table string, data map[string]any, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, table, data, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockwriterMockRecorder) Insert(ctx, table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*Mockwriter)(nil).Insert), ctx, table, data, opts)
}

// Inserts mocks base method.
func (m *Mockwriter) Inserts(ctx context.Context, table string, data []map[string]any, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inserts", ctx, table, data, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inserts indicates an expected call of Inserts.
func (mr *MockwriterMockRecorder) Inserts(ctx, table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inserts", reflect.TypeOf((*Mockwriter)(nil).Inserts), ctx, table, data, opts)
}

// Update mocks base method.
func (m *Mockwriter) Update(ctx context.Context, table string, data map[string]any, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, table, data, joins, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockwriterMockRecorder) Update(ctx, table, data, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mockwriter)(nil).Update), ctx, table, data, joins, conditions, opts)
}

// Mockupserter is a mock of upserter interface.
type Mockupserter struct {
	ctrl     *gomock.Controller
	recorder *MockupserterMockRecorder
}

// MockupserterMockRecorder is the mock recorder for Mockupserter.
type MockupserterMockRecorder struct {
	mock *Mockupserter
}

// NewMockupserter creates a new mock instance.
func NewMockupserter(ctrl *gomock.Controller) *Mockupserter {
	mock := &Mockupserter{ctrl: ctrl}
	mock.recorder = &MockupserterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockupserter) EXPECT() *MockupserterMockRecorder {
	return m.recorder
}

// Upsert mocks base method.
func (m *Mockupserter) Upsert(ctx context.Context, table string, data map[string]any, upsertOpts *options.UpsertOptions, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, table, data, upsertOpts, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockupserterMockRecorder) Upsert(ctx, table, data, upsertOpts, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*Mockupserter)(nil).Upsert), ctx, table, data, upsertOpts, opts)
}

// UpsertQuery mocks base method.
func (m *Mockupserter) UpsertQuery(table string, data map[string]any, upsertOpts *options.UpsertOptions, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertQuery", table, data, upsertOpts, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpsertQuery indicates an expected call of UpsertQuery.
func (mr *MockupserterMockRecorder) UpsertQuery(table, data, upsertOpts, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertQuery", reflect.TypeOf((*Mockupserter)(nil).UpsertQuery), table, data, upsertOpts, opts)
}

// Mockintrospector is a mock of introspector interface.
type Mockintrospector struct {
	ctrl     *gomock.Controller
	recorder *MockintrospectorMockRecorder
}

// MockintrospectorMockRecorder is the mock recorder for Mockintrospector.
type MockintrospectorMockRecorder struct {
	mock *Mockintrospector
}

// NewMockintrospector creates a new mock instance.
func NewMockintrospector(ctrl *gomock.Controller) *Mockintrospector {
	mock := &Mockintrospector{ctrl: ctrl}
	mock.recorder = &MockintrospectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockintrospector) EXPECT() *MockintrospectorMockRecorder {
	return m.recorder
}

// DeleteQuery mocks base method.
func (m *Mockintrospector) DeleteQuery(table string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuery", table, joins, conditions, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteQuery indicates an expected call of DeleteQuery.
func (mr *MockintrospectorMockRecorder) DeleteQuery(table, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuery", reflect.TypeOf((*Mockintrospector)(nil).DeleteQuery), table, joins, conditions, opts)
}

// Explain mocks base method.
func (m *Mockintrospector) Explain(ctx context.Context, query string, args ...any) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Explain", varargs...)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Explain indicates an expected call of Explain.
func (mr *MockintrospectorMockRecorder) Explain(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Explain", reflect.TypeOf((*Mockintrospector)(nil).Explain), varargs...)
}

// GetByIDQuery mocks base method.
func (m *Mockintrospector) GetByIDQuery(table string, id any, joins []condition.Join, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDQuery", table, id, joins, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByIDQuery indicates an expected call of GetByIDQuery.
func (mr *MockintrospectorMockRecorder) GetByIDQuery(table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDQuery", reflect.TypeOf((*Mockintrospector)(nil).GetByIDQuery), table, id, joins, opts)
}

// GetQuery mocks base method.
func (m *Mockintrospector) GetQuery(table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuery", table, columns, joins, conditions, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetQuery indicates an expected call of GetQuery.
func (mr *MockintrospectorMockRecorder) GetQuery(table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuery", reflect.TypeOf((*Mockintrospector)(nil).GetQuery), table, columns, joins, conditions, opts)
}

// InsertQuery mocks base method.
func (m *Mockintrospector) InsertQuery(table string, data map[string]any, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertQuery", table, data, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InsertQuery indicates an expected call of InsertQuery.
func (mr *MockintrospectorMockRecorder) InsertQuery(table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertQuery", reflect.TypeOf((*Mockintrospector)(nil).InsertQuery), table, data, opts)
}

// InsertsQuery mocks base method.
func (m *Mockintrospector) InsertsQuery(table string, data []map[string]any, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertsQuery", table, data, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InsertsQuery indicates an expected call of InsertsQuery.
func (mr *MockintrospectorMockRecorder) InsertsQuery(table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertsQuery", reflect.TypeOf((*Mockintrospector)(nil).InsertsQuery), table, data, opts)
}

// UpdateQuery mocks base method.
func (m *Mockintrospector) UpdateQuery(table string, data map[string]any, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuery", table, data, joins, conditions, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateQuery indicates an expected call of UpdateQuery.
func (mr *MockintrospectorMockRecorder) UpdateQuery(table, data, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuery", reflect.TypeOf((*Mockintrospector)(nil).UpdateQuery), table, data, joins, conditions, opts)
}

// Mocktransactional is a mock of transactional interface.
type Mocktransactional struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionalMockRecorder
}

// MocktransactionalMockRecorder is the mock recorder for Mocktransactional.
type MocktransactionalMockRecorder struct {
	mock *Mocktransactional
}

// NewMocktransactional creates a new mock instance.
func NewMocktransactional(ctrl *gomock.Controller) *Mocktransactional {
	mock := &Mocktransactional{ctrl: ctrl}
	mock.recorder = &MocktransactionalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktransactional) EXPECT() *MocktransactionalMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *Mocktransactional) Begin(ctx context.Context, opts ...TransactionOptions) (Tx, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Begin", varargs...)
	ret0, _ := ret[0].(Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MocktransactionalMockRecorder) Begin(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*Mocktransactional)(nil).Begin), varargs...)
}

// WithTransaction mocks base method.
func (m *Mocktransactional) WithTransaction(ctx context.Context, fn func(Tx) error, opts ...TransactionOptions) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, fn}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithTransaction", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MocktransactionalMockRecorder) WithTransaction(ctx, fn interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, fn}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*Mocktransactional)(nil).WithTransaction), varargs...)
}

// Mocksavepointer is a mock of savepointer interface.
type Mocksavepointer struct {
	ctrl     *gomock.Controller
	recorder *MocksavepointerMockRecorder
}

// MocksavepointerMockRecorder is the mock recorder for Mocksavepointer.
type MocksavepointerMockRecorder struct {
	mock *Mocksavepointer
}

// NewMocksavepointer creates a new mock instance.
func NewMocksavepointer(ctrl *gomock.Controller) *Mocksavepointer {
	mock := &Mocksavepointer{ctrl: ctrl}
	mock.recorder = &MocksavepointerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksavepointer) EXPECT() *MocksavepointerMockRecorder {
	return m.recorder
}

// ReleaseSavepoint mocks base method.
func (m *Mocksavepointer) ReleaseSavepoint(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseSavepoint", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseSavepoint indicates an expected call of ReleaseSavepoint.
func (mr *MocksavepointerMockRecorder) ReleaseSavepoint(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseSavepoint", reflect.TypeOf((*Mocksavepointer)(nil).ReleaseSavepoint), ctx, name)
}

// RollbackToSavepoint mocks base method.
func (m *Mocksavepointer) RollbackToSavepoint(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackToSavepoint", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackToSavepoint indicates an expected call of RollbackToSavepoint.
func (mr *MocksavepointerMockRecorder) RollbackToSavepoint(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackToSavepoint", reflect.TypeOf((*Mocksavepointer)(nil).RollbackToSavepoint), ctx, name)
}

// Savepoint mocks base method.
func (m *Mocksavepointer) Savepoint(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Savepoint", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Savepoint indicates an expected call of Savepoint.
func (mr *MocksavepointerMockRecorder) Savepoint(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Savepoint", reflect.TypeOf((*Mocksavepointer)(nil).Savepoint), ctx, name)
}

// MockhealthCheck is a mock of healthCheck interface.
type MockhealthCheck struct {
	ctrl     *gomock.Controller
	recorder *MockhealthCheckMockRecorder
}

// MockhealthCheckMockRecorder is the mock recorder for MockhealthCheck.
type MockhealthCheckMockRecorder struct {
	mock *MockhealthCheck
}

// NewMockhealthCheck creates a new mock instance.
func NewMockhealthCheck(ctrl *gomock.Controller) *MockhealthCheck {
	mock := &MockhealthCheck{ctrl: ctrl}
	mock.recorder = &MockhealthCheckMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhealthCheck) EXPECT() *MockhealthCheckMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockhealthCheck) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockhealthCheckMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockhealthCheck)(nil).Ping), ctx)
}

// PoolStats mocks base method.
func (m *MockhealthCheck) PoolStats() (*PoolStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PoolStats")
	ret0, _ := ret[0].(*PoolStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PoolStats indicates an expected call of PoolStats.
func (mr *MockhealthCheckMockRecorder) PoolStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PoolStats", reflect.TypeOf((*MockhealthCheck)(nil).PoolStats))
}

// Mockcloser is a mock of closer interface.
type Mockcloser struct {
	ctrl     *gomock.Controller
	recorder *MockcloserMockRecorder
}

// MockcloserMockRecorder is the mock recorder for Mockcloser.
type MockcloserMockRecorder struct {
	mock *Mockcloser
}

// NewMockcloser creates a new mock instance.
func NewMockcloser(ctrl *gomock.Controller) *Mockcloser {
	mock := &Mockcloser{ctrl: ctrl}
	mock.recorder = &MockcloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcloser) EXPECT() *MockcloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *Mockcloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockcloserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Mockcloser)(nil).Close))
}

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDB) Begin(ctx context.Context, opts ...TransactionOptions) (Tx, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Begin", varargs...)
	ret0, _ := ret[0].(Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockDBMockRecorder) Begin(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDB)(nil).Begin), varargs...)
}

// Close mocks base method.
func (m *MockDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDB)(nil).Close))
}

// Delete mocks base method.
func (m *MockDB) Delete(ctx context.Context, table string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, table, joins, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDBMockRecorder) Delete(ctx, table, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDB)(nil).Delete), ctx, table, joins, conditions, opts)
}

// DeleteQuery mocks base method.
func (m *MockDB) DeleteQuery(table string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuery", table, joins, conditions, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteQuery indicates an expected call of DeleteQuery.
func (mr *MockDBMockRecorder) DeleteQuery(table, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuery", reflect.TypeOf((*MockDB)(nil).DeleteQuery), table, joins, conditions, opts)
}

// Exec mocks base method.
func (m *MockDB) Exec(ctx context.Context, query string, args ...any) (*ExecResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBMockRecorder) Exec(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDB)(nil).Exec), varargs...)
}

// Explain mocks base method.
func (m *MockDB) Explain(ctx context.Context, query string, args ...any) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Explain", varargs...)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Explain indicates an expected call of Explain.
func (mr *MockDBMockRecorder) Explain(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Explain", reflect.TypeOf((*MockDB)(nil).Explain), varargs...)
}

// Get mocks base method.
func (m *MockDB) Get(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDBMockRecorder) Get(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDB)(nil).Get), ctx, table, columns, joins, conditions, opts)
}

// GetByID mocks base method.
func (m *MockDB) GetByID(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, table, id, joins, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDBMockRecorder) GetByID(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDB)(nil).GetByID), ctx, table, id, joins, opts)
}

// GetByIDQuery mocks base method.
func (m *MockDB) GetByIDQuery(table string, id any, joins []condition.Join, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDQuery", table, id, joins, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByIDQuery indicates an expected call of GetByIDQuery.
func (mr *MockDBMockRecorder) GetByIDQuery(table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDQuery", reflect.TypeOf((*MockDB)(nil).GetByIDQuery), table, id, joins, opts)
}

// GetByIDRaw mocks base method.
func (m *MockDB) GetByIDRaw(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDRaw", ctx, table, id, joins, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDRaw indicates an expected call of GetByIDRaw.
func (mr *MockDBMockRecorder) GetByIDRaw(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDRaw", reflect.TypeOf((*MockDB)(nil).GetByIDRaw), ctx, table, id, joins, opts)
}

// GetQuery mocks base method.
func (m *MockDB) GetQuery(table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuery", table, columns, joins, conditions, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetQuery indicates an expected call of GetQuery.
func (mr *MockDBMockRecorder) GetQuery(table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuery", reflect.TypeOf((*MockDB)(nil).GetQuery), table, columns, joins, conditions, opts)
}

// GetRaw mocks base method.
func (m *MockDB) GetRaw(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRaw", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRaw indicates an expected call of GetRaw.
func (mr *MockDBMockRecorder) GetRaw(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRaw", reflect.TypeOf((*MockDB)(nil).GetRaw), ctx, table, columns, joins, conditions, opts)
}

// Insert mocks base method.
func (m *MockDB) Insert(ctx context.Context, table string, data map[string]any, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, table, data, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockDBMockRecorder) Insert(ctx, table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDB)(nil).Insert), ctx, table, data, opts)
}

// InsertQuery mocks base method.
func (m *MockDB) InsertQuery(table string, data map[string]any, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertQuery", table, data, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InsertQuery indicates an expected call of InsertQuery.
func (mr *MockDBMockRecorder) InsertQuery(table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertQuery", reflect.TypeOf((*MockDB)(nil).InsertQuery), table, data, opts)
}

// Inserts mocks base method.
func (m *MockDB) Inserts(ctx context.Context, table string, data []map[string]any, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inserts", ctx, table, data, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inserts indicates an expected call of Inserts.
func (mr *MockDBMockRecorder) Inserts(ctx, table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inserts", reflect.TypeOf((*MockDB)(nil).Inserts), ctx, table, data, opts)
}

// InsertsQuery mocks base method.
func (m *MockDB) InsertsQuery(table string, data []map[string]any, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertsQuery", table, data, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InsertsQuery indicates an expected call of InsertsQuery.
func (mr *MockDBMockRecorder) InsertsQuery(table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertsQuery", reflect.TypeOf((*MockDB)(nil).InsertsQuery), table, data, opts)
}

// Ping mocks base method.
func (m *MockDB) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDBMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDB)(nil).Ping), ctx)
}

// PoolStats mocks base method.
func (m *MockDB) PoolStats() (*PoolStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PoolStats")
	ret0, _ := ret[0].(*PoolStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PoolStats indicates an expected call of PoolStats.
func (mr *MockDBMockRecorder) PoolStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PoolStats", reflect.TypeOf((*MockDB)(nil).PoolStats))
}

// Query mocks base method.
func (m *MockDB) Query(ctx context.Context, query string, args ...any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDBMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDB)(nil).Query), varargs...)
}

// QueryRaw mocks base method.
func (m *MockDB) QueryRaw(ctx context.Context, query string, args ...any) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRaw", varargs...)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryRaw indicates an expected call of QueryRaw.
func (mr *MockDBMockRecorder) QueryRaw(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRaw", reflect.TypeOf((*MockDB)(nil).QueryRaw), varargs...)
}

// Update mocks base method.
func (m *MockDB) Update(ctx context.Context, table string, data map[string]any, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, table, data, joins, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDBMockRecorder) Update(ctx, table, data, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDB)(nil).Update), ctx, table, data, joins, conditions, opts)
}

// UpdateQuery mocks base method.
func (m *MockDB) UpdateQuery(table string, data map[string]any, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuery", table, data, joins, conditions, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateQuery indicates an expected call of UpdateQuery.
func (mr *MockDBMockRecorder) UpdateQuery(table, data, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuery", reflect.TypeOf((*MockDB)(nil).UpdateQuery), table, data, joins, conditions, opts)
}

// Upsert mocks base method.
func (m *MockDB) Upsert(ctx context.Context, table string, data map[string]any, upsertOpts *options.UpsertOptions, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, table, data, upsertOpts, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDBMockRecorder) Upsert(ctx, table, data, upsertOpts, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDB)(nil).Upsert), ctx, table, data, upsertOpts, opts)
}

// UpsertQuery mocks base method.
func (m *MockDB) UpsertQuery(table string, data map[string]any, upsertOpts *options.UpsertOptions, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertQuery", table, data, upsertOpts, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpsertQuery indicates an expected call of UpsertQuery.
func (mr *MockDBMockRecorder) UpsertQuery(table, data, upsertOpts, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertQuery", reflect.TypeOf((*MockDB)(nil).UpsertQuery), table, data, upsertOpts, opts)
}

// WithTransaction mocks base method.
func (m *MockDB) WithTransaction(ctx context.Context, fn func(Tx) error, opts ...TransactionOptions) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, fn}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithTransaction", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockDBMockRecorder) WithTransaction(ctx, fn interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, fn}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockDB)(nil).WithTransaction), varargs...)
}

// MockTx is a mock of Tx interface.
type MockTx struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder struct {
	mock *MockTx
}

// NewMockTx creates a new mock instance.
func NewMockTx(ctrl *gomock.Controller) *MockTx {
	mock := &MockTx{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx) EXPECT() *MockTxMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTx) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxMockRecorder) Commit(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTx)(nil).Commit), ctx)
}

// Delete mocks base method.
func (m *MockTx) Delete(ctx context.Context, table string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, table, joins, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTxMockRecorder) Delete(ctx, table, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTx)(nil).Delete), ctx, table, joins, conditions, opts)
}

// DeleteQuery mocks base method.
func (m *MockTx) DeleteQuery(table string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuery", table, joins, conditions, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteQuery indicates an expected call of DeleteQuery.
func (mr *MockTxMockRecorder) DeleteQuery(table, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuery", reflect.TypeOf((*MockTx)(nil).DeleteQuery), table, joins, conditions, opts)
}

// Exec mocks base method.
func (m *MockTx) Exec(ctx context.Context, query string, args ...any) (*ExecResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockTxMockRecorder) Exec(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockTx)(nil).Exec), varargs...)
}

// Explain mocks base method.
func (m *MockTx) Explain(ctx context.Context, query string, args ...any) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Explain", varargs...)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Explain indicates an expected call of Explain.
func (mr *MockTxMockRecorder) Explain(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Explain", reflect.TypeOf((*MockTx)(nil).Explain), varargs...)
}

// Get mocks base method.
func (m *MockTx) Get(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTxMockRecorder) Get(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTx)(nil).Get), ctx, table, columns, joins, conditions, opts)
}

// GetByID mocks base method.
func (m *MockTx) GetByID(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, table, id, joins, opts)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTxMockRecorder) GetByID(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTx)(nil).GetByID), ctx, table, id, joins, opts)
}

// GetByIDQuery mocks base method.
func (m *MockTx) GetByIDQuery(table string, id any, joins []condition.Join, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDQuery", table, id, joins, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByIDQuery indicates an expected call of GetByIDQuery.
func (mr *MockTxMockRecorder) GetByIDQuery(table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDQuery", reflect.TypeOf((*MockTx)(nil).GetByIDQuery), table, id, joins, opts)
}

// GetByIDRaw mocks base method.
func (m *MockTx) GetByIDRaw(ctx context.Context, table string, id any, joins []condition.Join, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDRaw", ctx, table, id, joins, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDRaw indicates an expected call of GetByIDRaw.
func (mr *MockTxMockRecorder) GetByIDRaw(ctx, table, id, joins, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDRaw", reflect.TypeOf((*MockTx)(nil).GetByIDRaw), ctx, table, id, joins, opts)
}

// GetQuery mocks base method.
func (m *MockTx) GetQuery(table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuery", table, columns, joins, conditions, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetQuery indicates an expected call of GetQuery.
func (mr *MockTxMockRecorder) GetQuery(table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuery", reflect.TypeOf((*MockTx)(nil).GetQuery), table, columns, joins, conditions, opts)
}

// GetRaw mocks base method.
func (m *MockTx) GetRaw(ctx context.Context, table string, columns []string, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRaw", ctx, table, columns, joins, conditions, opts)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRaw indicates an expected call of GetRaw.
func (mr *MockTxMockRecorder) GetRaw(ctx, table, columns, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRaw", reflect.TypeOf((*MockTx)(nil).GetRaw), ctx, table, columns, joins, conditions, opts)
}

// Insert mocks base method.
func (m *MockTx) Insert(ctx context.Context, table string, data map[string]any, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, table, data, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockTxMockRecorder) Insert(ctx, table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTx)(nil).Insert), ctx, table, data, opts)
}

// InsertQuery mocks base method.
func (m *MockTx) InsertQuery(table string, data map[string]any, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertQuery", table, data, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InsertQuery indicates an expected call of InsertQuery.
func (mr *MockTxMockRecorder) InsertQuery(table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertQuery", reflect.TypeOf((*MockTx)(nil).InsertQuery), table, data, opts)
}

// Inserts mocks base method.
func (m *MockTx) Inserts(ctx context.Context, table string, data []map[string]any, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inserts", ctx, table, data, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inserts indicates an expected call of Inserts.
func (mr *MockTxMockRecorder) Inserts(ctx, table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inserts", reflect.TypeOf((*MockTx)(nil).Inserts), ctx, table, data, opts)
}

// InsertsQuery mocks base method.
func (m *MockTx) InsertsQuery(table string, data []map[string]any, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertsQuery", table, data, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InsertsQuery indicates an expected call of InsertsQuery.
func (mr *MockTxMockRecorder) InsertsQuery(table, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertsQuery", reflect.TypeOf((*MockTx)(nil).InsertsQuery), table, data, opts)
}

// Query mocks base method.
func (m *MockTx) Query(ctx context.Context, query string, args ...any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockTxMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockTx)(nil).Query), varargs...)
}

// QueryRaw mocks base method.
func (m *MockTx) QueryRaw(ctx context.Context, query string, args ...any) (*RowsAdapter, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRaw", varargs...)
	ret0, _ := ret[0].(*RowsAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryRaw indicates an expected call of QueryRaw.
func (mr *MockTxMockRecorder) QueryRaw(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRaw", reflect.TypeOf((*MockTx)(nil).QueryRaw), varargs...)
}

// ReleaseSavepoint mocks base method.
func (m *MockTx) ReleaseSavepoint(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseSavepoint", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseSavepoint indicates an expected call of ReleaseSavepoint.
func (mr *MockTxMockRecorder) ReleaseSavepoint(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseSavepoint", reflect.TypeOf((*MockTx)(nil).ReleaseSavepoint), ctx, name)
}

// Rollback mocks base method.
func (m *MockTx) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxMockRecorder) Rollback(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTx)(nil).Rollback), ctx)
}

// RollbackToSavepoint mocks base method.
func (m *MockTx) RollbackToSavepoint(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackToSavepoint", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackToSavepoint indicates an expected call of RollbackToSavepoint.
func (mr *MockTxMockRecorder) RollbackToSavepoint(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackToSavepoint", reflect.TypeOf((*MockTx)(nil).RollbackToSavepoint), ctx, name)
}

// Savepoint mocks base method.
func (m *MockTx) Savepoint(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Savepoint", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Savepoint indicates an expected call of Savepoint.
func (mr *MockTxMockRecorder) Savepoint(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Savepoint", reflect.TypeOf((*MockTx)(nil).Savepoint), ctx, name)
}

// Update mocks base method.
func (m *MockTx) Update(ctx context.Context, table string, data map[string]any, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, table, data, joins, conditions, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTxMockRecorder) Update(ctx, table, data, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTx)(nil).Update), ctx, table, data, joins, conditions, opts)
}

// UpdateQuery mocks base method.
func (m *MockTx) UpdateQuery(table string, data map[string]any, joins []condition.Join, conditions condition.Condition, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuery", table, data, joins, conditions, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateQuery indicates an expected call of UpdateQuery.
func (mr *MockTxMockRecorder) UpdateQuery(table, data, joins, conditions, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuery", reflect.TypeOf((*MockTx)(nil).UpdateQuery), table, data, joins, conditions, opts)
}

// Upsert mocks base method.
func (m *MockTx) Upsert(ctx context.Context, table string, data map[string]any, upsertOpts *options.UpsertOptions, opts *options.QueryOptions) (*ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, table, data, upsertOpts, opts)
	ret0, _ := ret[0].(*ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTxMockRecorder) Upsert(ctx, table, data, upsertOpts, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTx)(nil).Upsert), ctx, table, data, upsertOpts, opts)
}

// UpsertQuery mocks base method.
func (m *MockTx) UpsertQuery(table string, data map[string]any, upsertOpts *options.UpsertOptions, opts *options.QueryOptions) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertQuery", table, data, upsertOpts, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpsertQuery indicates an expected call of UpsertQuery.
func (mr *MockTxMockRecorder) UpsertQuery(table, data, upsertOpts, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertQuery", reflect.TypeOf((*MockTx)(nil).UpsertQuery), table, data, upsertOpts, opts)
}
