// Code generated by MockGen. DO NOT EDIT.
// Source: condition.go

// Package condition is a generated GoMock package.
package condition

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	definition "tounilab.com/fabric/pkg/query/definition"
	options "tounilab.com/fabric/pkg/query/options"
)

// MockCondition is a mock of Condition interface.
type MockCondition struct {
	ctrl     *gomock.Controller
	recorder *MockConditionMockRecorder
}

// MockConditionMockRecorder is the mock recorder for MockCondition.
type MockConditionMockRecorder struct {
	mock *MockCondition
}

// NewMockCondition creates a new mock instance.
func NewMockCondition(ctrl *gomock.Controller) *MockCondition {
	mock := &MockCondition{ctrl: ctrl}
	mock.recorder = &MockConditionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCondition) EXPECT() *MockConditionMockRecorder {
	return m.recorder
}

// ToSQL mocks base method.
func (m *MockCondition) ToSQL(dialect SQLDialect, paramBase int) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToSQL", dialect, paramBase)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ToSQL indicates an expected call of ToSQL.
func (mr *MockConditionMockRecorder) ToSQL(dialect, paramBase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToSQL", reflect.TypeOf((*MockCondition)(nil).ToSQL), dialect, paramBase)
}

// MockSQLDialect is a mock of SQLDialect interface.
type MockSQLDialect struct {
	ctrl     *gomock.Controller
	recorder *MockSQLDialectMockRecorder
}

// MockSQLDialectMockRecorder is the mock recorder for MockSQLDialect.
type MockSQLDialectMockRecorder struct {
	mock *MockSQLDialect
}

// NewMockSQLDialect creates a new mock instance.
func NewMockSQLDialect(ctrl *gomock.Controller) *MockSQLDialect {
	mock := &MockSQLDialect{ctrl: ctrl}
	mock.recorder = &MockSQLDialectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLDialect) EXPECT() *MockSQLDialectMockRecorder {
	return m.recorder
}

// Operator mocks base method.
func (m *MockSQLDialect) Operator(op string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Operator", op)
	ret0, _ := ret[0].(string)
	return ret0
}

// Operator indicates an expected call of Operator.
func (mr *MockSQLDialectMockRecorder) Operator(op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Operator", reflect.TypeOf((*MockSQLDialect)(nil).Operator), op)
}

// Placeholder mocks base method.
func (m *MockSQLDialect) Placeholder(index int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Placeholder", index)
	ret0, _ := ret[0].(string)
	return ret0
}

// Placeholder indicates an expected call of Placeholder.
func (mr *MockSQLDialectMockRecorder) Placeholder(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Placeholder", reflect.TypeOf((*MockSQLDialect)(nil).Placeholder), index)
}

// QuoteIdentifier mocks base method.
func (m *MockSQLDialect) QuoteIdentifier(value string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuoteIdentifier", value)
	ret0, _ := ret[0].(string)
	return ret0
}

// QuoteIdentifier indicates an expected call of QuoteIdentifier.
func (mr *MockSQLDialectMockRecorder) QuoteIdentifier(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuoteIdentifier", reflect.TypeOf((*MockSQLDialect)(nil).QuoteIdentifier), value)
}

// QuoteString mocks base method.
func (m *MockSQLDialect) QuoteString(value string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuoteString", value)
	ret0, _ := ret[0].(string)
	return ret0
}

// QuoteString indicates an expected call of QuoteString.
func (mr *MockSQLDialectMockRecorder) QuoteString(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuoteString", reflect.TypeOf((*MockSQLDialect)(nil).QuoteString), value)
}

// SupportedOptions mocks base method.
func (m *MockSQLDialect) SupportedOptions(queryType definition.QueryType, opts *options.QueryOptions, paramBase int) (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedOptions", queryType, opts, paramBase)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SupportedOptions indicates an expected call of SupportedOptions.
func (mr *MockSQLDialectMockRecorder) SupportedOptions(queryType, opts, paramBase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedOptions", reflect.TypeOf((*MockSQLDialect)(nil).SupportedOptions), queryType, opts, paramBase)
}
