package sqldialect

const (
	equal                   = "eq"
	notEqual                = "neq"
	lowerThan               = "lt"
	lowerThanOrEqual        = "lte"
	greaterThan             = "gt"
	greaterThanOrEqual      = "gte"
	like                    = "like"
	notLike                 = "not like"
	insensitiveCaseLike     = "ilike"
	in                      = "in"
	notIn                   = "not in"
	between                 = "between"
	notBetween              = "not between"
	isNull                  = "is null"
	isNotNull               = "is not null"
	distinct                = "distinct"
	notDistinct             = "not distinct"
	isDistinctFrom          = "is distinct from"
	contains                = "contains"
	contained               = "contained"
	overlaps                = "overlaps"
	regex                   = "regex"
	notRegex                = "not regex"
	insensitiveCaseRegex    = "iregex"
	notInsensitiveCaseRegex = "not iregex"
)
